# Generated by Django 3.0.5 on 2020-05-24 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 24, 3, 16, 39, 533175, tzinfo=utc)),
        ),
    ]
