# Generated by Django 3.0.5 on 2020-05-24 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealtoorder',
            name='mealset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealset', to='orders.Meals_to_order'),
        ),
        migrations.AddField(
            model_name='meals_to_order',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderid', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='check',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicefee', to='orders.ServicePercentage'),
        ),
    ]
